### PR TITLE
Add ual-meetone integration example

### PR DESCRIPTION
**Pull request by DBingo**
## Change Description
Add `ual-meetone` integration example.

### CODE REVIEW

**Comment by wpwood** [comment]
Thanks for the pull request. Just FYI, since this is the first PR we've received on this repo, it may take a day or two for evaluate and merge. Thanks for contributing!

**Comment by TaraTritt** [comment]
Hi @DBingo, thanks for the PR! When attempting to use a modified Tropical Example to use mainnet and the `eosio.token::transfer` action on the MEET.ONE app, I received this alert:
meet one
Is this the expected behavior?

**Comment by TaraTritt** [comment]
@DBingo just a heads up this PR should be opened against the `develop` branch first, as detailed in the [Contributing Guide](https://github.com/EOSIO/tropical-example-web-app/blob/master/CONTRIBUTING.md#feature-branches)

**Comment by GreenBusDriver** [comment]
@DBingo We haven't heard anything in a long time.  Please check in, respond to the question above and re-create the PR, or we'll have to close this due to lack of response.

**Pull request closed without merging**
